import { defineStore } from 'pinia'

export const RouteSearchStore = defineStore('route', {
  state: () => ({
       caritems: [
            { title: '6', class: 'city', stop1: '干城站', stop2: '忠義里', startimg1: './image/route/6.png', startimg2: './image/route/2.6.png' },
            { title: '6副', class: 'city', stop1: '干城站', stop2: '原民中心', startimg1: './image/route/6.1.png', startimg2: './image/route/2.6.1.png' },
            { title: '8', class: 'city', stop1: '臺中刑務所演武場', stop2: '逢甲大學', startimg1: './image/route/8.png', startimg2: './image/route/2.8.png' },
            { title: '11', class: 'city', stop1: '臺中車站(民族路口)', stop2: '綠能街車(右環)', startimg1: './image/route/11.png', startimg2: './image/route/2.11.png' },
            { title: '12', class: 'city', stop1: '明德高中', stop2: '豐原高中', startimg1: './image/route/12.png', startimg2: './image/route/2.12.png' },
            { title: '14', class: 'city', stop1: '干城站', stop2: '舊庄(南清宮)', startimg1: './image/route/14.png', startimg2: './image/route/2.14.png' },
            { title: '14副', class: 'city', stop1: '干城站', stop2: '神岡區公所', startimg1: './image/route/14.1.png', startimg2: './image/route/2.14.1.png' },
            { title: '15', class: 'city', stop1: '臺中刑務所演武場', stop2: '國軍臺中總醫院', startimg1: './image/route/15.png', startimg2: './image/route/2.15.png' },
            { title: '26', class: 'city', stop1: '新民高中', stop2: '嶺東科技大學', startimg1: './image/route/26.png', startimg2: './image/route/2.26.png' },
            { title: '27', class: 'city', stop1: '臺中車站', stop2: '嶺東科技大學', startimg1: './image/route/27.png', startimg2: './image/route/2.27.png' },
            { title: '28', class: 'city', stop1: '坪頂', stop2: '四張犁圖書館', startimg1: './image/route/28.png', startimg2: './image/route/2.28.png' },
            { title: '29', class: 'city', stop1: '臺中監獄', stop2: '第一廣場', startimg1: './image/route/29.png', startimg2: './image/route/2.29.png' },
            { title: '33', class: 'city', stop1: '文修停車場', stop2: '高鐵臺中站', startimg1: './image/route/33.png', startimg2: './image/route/2.33.png' },
            { title: '35', class: 'city', stop1: '僑光科技大學', stop2: '南區公所', startimg1: './image/route/35.png', startimg2: './image/route/2.35.png' },
            { title: '41', class: 'city', stop1: '公共資訊圖書館', stop2: '修平科技大學', startimg1: './image/route/41.png', startimg2: './image/route/2.41.png' },
            { title: '54', class: 'city', stop1: '下港尾', stop2: '烏日', startimg1: './image/route/54.png', startimg2: './image/route/2.54.png' },
            { title: '60', class: 'city', stop1: '大智公園', stop2: '坪頂', startimg1: './image/route/60.png', startimg2: './image/route/2.60.png' },
            { title: '66', class: 'city', stop1: '潭子聯合辦公大樓', stop2: '大坑', startimg1: './image/route/66.png', startimg2: './image/route/2.66.png' },
            { title: '66副', class: 'city', stop1: '松竹車站', stop2: '大坑', startimg1: './image/route/66.1.png', startimg2: './image/route/2.66.1.png' },
            { title: '69', class: 'city', stop1: '龍潭里', stop2: '臺中國際機場', startimg1: './image/route/69.png', startimg2: './image/route/2.69.png' },
            { title: '70', class: 'city', stop1: '嶺東科技大學', stop2: '綠川東站', startimg1: './image/route/70.png', startimg2: './image/route/2.70.png' },
            { title: '72', class: 'city', stop1: '嶺東科技大學', stop2: '潭子聯合辦公大樓', startimg1: './image/route/72.png', startimg2: './image/route/2.72.png' },
            { title: '82', class: 'city', stop1: '貿易三村', stop2: '臺中車站', startimg1: './image/route/82.png', startimg2: './image/route/2.82.png' },
            { title: '82延', class: 'city', stop1: '貿易三村', stop2: '高鐵臺中站', startimg1: './image/route/82.2.png', startimg2: './image/route/2.82.2.png' },
            { title: '93', class: 'city', stop1: '新烏日車站', stop2: '銅安厝', startimg1: './image/route/93.png', startimg2: './image/route/2.93.png'},
            { title: '97', class: 'city', stop1: '國立苑裡高中', stop2: '臺中國際機場', startimg1: './image/route/97.png', startimg2: './image/route/2.97.png' },
            { title: '100', class: 'city', stop1: '高鐵臺中站', stop2: '臺中車站', startimg1: './image/route/100.png' },
            { title: '101', class: 'city', stop1: '敦化后庄七街口', stop2: '彰化', startimg1: './image/route/101.png', startimg2: './image/route/2.101.png' },
            { title: '107', class: 'city', stop1: '黎明新村', stop2: '舊正(烏溪橋頭)', startimg1: './image/route/107.png', startimg2: './image/route/2.107.png' },
            { title: '108', class: 'city', stop1: '港尾', stop2: '南開科技大學校區', startimg1: './image/route/108.png', startimg2: './image/route/2.108.png' },
            { title: '128', class: 'city', stop1: '大雅', stop2: '清水', startimg1: './image/route/128.png', startimg2: './image/route/2.128.png' },
            { title: '131', class: 'city', stop1: '北屯區行政大樓', stop2: '朝陽科技大學(經塗城路)', startimg1: './image/route/131.png', startimg2: './image/route/2.131.png' },
            { title: '132', class: 'city', stop1: '北屯區行政大樓', stop2: '朝陽科技大學', startimg1: './image/route/132.png', startimg2: './image/route/2.132.png' },
            { title: '133', class: 'city', stop1: '新烏日車站', stop2: '朝陽科技大學', startimg1: './image/route/133.png', startimg2: './image/route/2.133.png' },
            { title: '142', class: 'city', stop1: '豐年社區三站', stop2: '第一廣場', startimg1: './image/route/142.png', startimg2: './image/route/2.142.png' },
            { title: '154', class: 'city', stop1: '臺中女中', stop2: '大甲區公所', startimg1: './image/route/154.png', startimg2: './image/route/2.154.png' },
            { title: '156', class: 'city', stop1: '臺中國際機場', stop2: '高鐵臺中站', startimg1: './image/route/156.png', startimg2: './image/route/2.156.png' },
            { title: '157', class: 'city', stop1: '文心森林公園', stop2: '大甲區公所', startimg1: './image/route/157.png', startimg2: './image/route/2.157.png' },
            { title: '163', class: 'city', stop1: '國軍英雄館', stop2: '華盛頓中學', startimg1: './image/route/163.png', startimg2: './image/route/2.163.png' },
            { title: '200', class: 'city', stop1: '柳豐路(亞大醫院)', stop2: '新民高中', startimg1: './image/route/200.png' },
            { title: '200跳蛙公車', class: 'city', stop1: '亞大醫院', stop2: '臺中女中', startimg1: './image/route/200.2.png', startimg2: './image/route/2.200.2.png' },
            { title: '243', class: 'city', stop1: '東山高中', stop2: '亞洲大學安藤館', startimg1: './image/route/243.png', startimg2: './image/route/2.243.png' },
            { title: '245(含繞)', class: 'city', stop1: '頂街', stop2: '亞大醫院', startimg1: './image/route/245.png', startimg2: './image/route/2.245.png' },
            { title: '248', class: 'city', stop1: '新烏日車站', stop2: '修平科技大學', startimg1: './image/route/248.png', startimg2: './image/route/2.248.png' },
            { title: '284', class: 'city', stop1: '臺中車站', stop2: '修平科技大學', startimg1: './image/route/284.png', startimg2: './image/route/2.284.png' },
            { title: '290', class: 'city', stop1: '干城站', stop2: '童綜合醫院(梧棲院區)', startimg1: './image/route/290.png', startimg2: './image/route/2.290.png' },
            { title: '300', class: 'city', stop1: '靜宜大學', stop2: '臺中車站', startimg1: './image/route/300.png' },
            { title: '304', class: 'city', stop1: '港區藝術中心', stop2: '新民高中', startimg1: './image/route/304.png' },
            { title: '307', class: 'city', stop1: '梧棲觀光漁港', stop2: '新民高中', startimg1: './image/route/307.png', startimg2: './image/route/2.307.png' },
            { title: '307副', class: 'city', stop1: '四維港新五路口', stop2: '臺中車站(臺灣大道)', startimg1: './image/route/307.1.png', startimg2: './image/route/2.307.1.png' },
            { title: '309', class: 'city', stop1: '高美濕地', stop2: '臺中車站', startimg1: './image/route/309.png', startimg2: './image/route/2.309.png' },
            { title: '310', class: 'city', stop1: '臺中港旅客服務中心', stop2: '臺中車站', startimg1: './image/route/310.png' },
            { title: '323', class: 'city', stop1: '彩虹眷村', stop2: '新建國市場', startimg1: './image/route/323.png', startimg2: './image/route/2.323.png' },
            { title: '324', class: 'city', stop1: '臺中都會公園', stop2: '臺中車站', startimg1: './image/route/324.png', startimg2: './image/route/2.324.png' },
            { title: '325', class: 'city', stop1: '大肚車站', stop2: '臺中車站', startimg1: './image/route/325.png', startimg2: './image/route/2.325.png' },
            { title: '357', class: 'city', stop1: '臺中國際機場', stop2: '中台新村', startimg1: './image/route/357.png', startimg2: './image/route/2.357.png' },
            { title: '365(代駛)', class: 'city', stop1: '高鐵臺中站', stop2: '國安社區', startimg1: './image/route/365.png' },
            { title: '500', class: 'city', stop1: '臺中國際機場', stop2: '臺中車站', startimg1: './image/route/500.png' },
            { title: '500延', class: 'city', stop1: '三田國小', stop2: '臺中車站', startimg1: './image/route/500.11.png' },
            { title: '500延區1', class: 'city', stop1: '大雅', stop2: '三田國小', startimg1: './image/route/500.12.png' },
            { title: '500延區2', class: 'city', stop1: '臺中車站', stop2: '臺中車站', startimg1: './image/route/500.13.png', startimg2: './image/route/2.500.13.png' },
            { title: '500延區3', class: 'city', stop1: '三田國小', stop2: '臺中車站', startimg1: './image/route/500.14.png' },
            { title: '500跳蛙公車', class: 'city', stop1: '忠義里', stop2: '臺中車站', startimg1: './image/route/500.2.png', startimg2: './image/route/2.500.2.png' },
            { title: '657', class: 'city', stop1: '大甲高工', stop2: '建興', startimg1: './image/route/657.png', startimg2: './image/route/2.657.png' },
            { title: '659', class: 'city', stop1: '幼獅工業區服務中心', stop2: '臺中榮總', startimg1: './image/route/659.png', startimg2: './image/route/2.659.png' },
            { title: '675', class: 'city', stop1: '龍津高中', stop2: '凱旋敦化路口', startimg1: './image/route/675.png', startimg2: './image/route/2.675.png' },
            { title: '700跳蛙公車', class: 'city', stop1: '明德高中', stop2: '豐原高中', startimg1: './image/route/700.2.png', startimg2: './image/route/2.700.2.png' },
            { title: '811', class: 'city', stop1: '豐原東站', stop2: '大甲體育場', startimg1: './image/route/811.png', startimg2: './image/route/2.811.png' },
            { title: '901', class: 'city', stop1: '豐村國小(經豐東路)', stop2: '明德高中', startimg1: './image/route/901.png', startimg2: './image/route/2.901.png' },
            { title: '901副', class: 'city', stop1: '豐村國小(經豐原大道)', stop2: '明德高中', startimg1: './image/route/901.1.png', startimg2: './image/route/2.901.1.png' },
            { title: '901副2', class: 'city', stop1: '豐村國小(繞敦富路)', stop2: '明德高中', startimg1: './image/route/901.2.png', startimg2: './image/route/2.901.2.png' },
            { title: '6899', class: 'high', stop1: '台中', stop2: '埔里', startimg1: './image/route/6899.png' },
            { title: '6188', class: 'high', stop1: '台中', stop2: '竹山', startimg1: './image/route/6188.png', startimg2: './image/route/2.6188.png' },
            { title: '9010', class: 'high', stop1: '台中', stop2: '新竹', startimg1: './image/route/9010.png', startimg2: './image/route/2.9010.png' },
            { title: '9015', class: 'high', stop1: '台中', stop2: '北港', startimg1: './image/route/9015.png', startimg2: './image/route/2.9015.png' },
            { title: '9016', class: 'high', stop1: '台中', stop2: '四湖', startimg1: './image/route/9016.png', startimg2: './image/route/2.9016.png' },
        ],
  }),
})